import Deck from "../class/deck";
import DeckLookup from "./deckOfCardsLookup";
export default function PlayingCardsCards() {
  let playingCards = new Deck([
    DeckLookup(0),
    DeckLookup(1),
    DeckLookup(2),
    DeckLookup(3),
    DeckLookup(4),
    DeckLookup(5),
    DeckLookup(6),
    DeckLookup(7),
    DeckLookup(8),
    DeckLookup(9),
    DeckLookup(10),
    DeckLookup(11),
    DeckLookup(12),
    DeckLookup(13),
    DeckLookup(14),
    DeckLookup(15),
    DeckLookup(16),
    DeckLookup(17),
    DeckLookup(18),
    DeckLookup(19),
    DeckLookup(20),
    DeckLookup(21),
    DeckLookup(22),
    DeckLookup(23),
    DeckLookup(24),
    DeckLookup(25),
    DeckLookup(26),
    DeckLookup(27),
    DeckLookup(28),
    DeckLookup(29),
    DeckLookup(30),
    DeckLookup(31),
    DeckLookup(32),
    DeckLookup(33),
    DeckLookup(34),
    DeckLookup(35),
    DeckLookup(36),
    DeckLookup(37),
    DeckLookup(38),
    DeckLookup(39),
    DeckLookup(40),
    DeckLookup(41),
    DeckLookup(42),
    DeckLookup(43),
    DeckLookup(44),
    DeckLookup(45),
    DeckLookup(46),
    DeckLookup(47),
    DeckLookup(48),
    DeckLookup(49),
    DeckLookup(50),
    DeckLookup(51)
  ]);

  return playingCards;
}
